const { shouldGenerate } = require('../lib/generate');

describe('shouldGenerate', () => {
  it('should return true for empty body', () => {
    expect(shouldGenerate(null)).toBe(true);
    expect(shouldGenerate('')).toBe(true);
    expect(shouldGenerate('   ')).toBe(true);
  });

  it('should return false if it contains the footer', () => {
    expect(shouldGenerate('Some text\n📝 Generated by [PR Autopilot](https://pr-autopilot.vercel.app) — edit freely')).toBe(false);
  });

  it('should return false for substantial description', () => {
    const substantial = 'Line one is long enough\nLine two is also long enough\nLine three is the final one';
    expect(shouldGenerate(substantial)).toBe(false);
  });

  it('should return true for short description', () => {
    expect(shouldGenerate('Short one')).toBe(true);
    expect(shouldGenerate('One line\nTwo lines')).toBe(true);
  });
});
