/**
 * AI-powered PR description generator.
 * Uses Anthropic Claude to turn a diff + PR metadata into a structured description.
 */

const Anthropic = require('@anthropic-ai/sdk');

/**
 * Generate a structured PR description from a diff and PR metadata.
 */
async function generateDescription({ title, headBranch, baseBranch, diff, files }) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    throw new Error('ANTHROPIC_API_KEY is not set');
  }

  const client = new Anthropic({ apiKey });

  // How many diff characters to send to the model (avoid token limits)
  const MAX_DIFF_CHARS = 24_000;

  const truncatedDiff = diff
    ? diff.slice(0, MAX_DIFF_CHARS) + (diff.length > MAX_DIFF_CHARS ? '\n\n[diff truncated]' : '')
    : null;

  const filesSummary = files
    .map(f => `${(f.status || '').padEnd(8)} ${f.filename} (+${f.additions || 0}/-${f.deletions || 0})`)
    .join('\n');

  const prompt = `You are PR Autopilot, an AI that writes clear, helpful pull request descriptions for developers.

A developer just opened a PR and left the description empty (or nearly empty). Your job is to write a useful description that will help reviewers understand the change quickly.

## PR Metadata
- **Title**: ${title}
- **Branch**: \`${headBranch}\` → \`${baseBranch}\`

## Files Changed
\`\`\`
${filesSummary}
\`\`\`

${truncatedDiff ? `## Diff\n\`\`\`diff\n${truncatedDiff}\n\`\`\`` : ''}

---

Write a PR description in Markdown using this EXACT structure:

## What changed
[2-4 sentences describing the actual code changes in plain language. Be specific about what was added, removed, or modified. Not WHY — just WHAT.]

## Why
[1-3 sentences on the probable motivation inferred from the code. If it's a bug fix, say so. If it's a feature, describe it. If unclear, say "Purpose unclear from diff alone — please add context."]

## How to test
[Concrete testing steps. If it's a config/docs-only change, say "No functional changes — visual review only." If you can infer test scenarios from the code, list them as checkboxes.]

## Notes
[Optional: flag any concerns — missing tests, potential breaking changes, large scope, security implications, or anything reviewers should pay special attention to. If nothing notable, omit this section entirely.]

---

Rules:
- Write like a senior engineer, not a press release
- No fluff, no filler, no "This PR..." opener
- Use \`code\` formatting for file names, function names, and values
- Keep it under 300 words total
- Add a small footer: *📝 Generated by [PR Autopilot](https://pr-autopilot.vercel.app) — edit freely*`;

  const message = await client.messages.create({
    model: 'claude-3-5-haiku-20241022',
    max_tokens: 1024,
    messages: [{ role: 'user', content: prompt }],
  });

  return message.content[0].text;
}

/**
 * Decide whether a PR description is "empty enough" to warrant auto-generation.
 * Returns true if the description should be generated/replaced.
 */
function shouldGenerate(existingBody) {
  if (!existingBody) return true;
  const trimmed = existingBody.trim();
  if (trimmed.length === 0) return true;

  // Skip if already has our footer (avoid re-generating on edits)
  if (trimmed.includes('Generated by [PR Autopilot]')) return false;

  // Skip if the description is substantial (more than 3 non-empty lines)
  const meaningfulLines = trimmed.split('\n').filter(l => l.trim().length > 5);
  if (meaningfulLines.length >= 3) return false;

  // Otherwise (1-2 lines, placeholder text, etc.) — generate
  return true;
}

module.exports = { generateDescription, shouldGenerate };
